# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my-test-chat' do
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my-test-chat
  pod 'MessageKit', '~> 3.3.0'

  
end
